### ISSUE TITLE
support older and newer versions of virtualenv/pip

### ISSUE THREAD

**Issue by tgs** [Yelp/pip-faster#33]
This doesn't work with new versions of pip or virtualenv.  I got it to work by
* Making a bootstrap virtualenv, then installing virtualenv 1.11.6 in that, and
* Adding pip<2 to the list of dependencies in the beginning of venv_update.py

It also didn't work with the super-old virtualenv on my system (1.9.1), or the pip version that it installed (1.4.1).

**Comment by bukzor** [comment]
Thanks for the feedback!

You'll find that this is in my TODO for 1.0 https://github.com/Yelp/venv-update/blob/v0.1/TODO#L8

I'll make sure to cover the specific cases you mentioned.

I also mentioned using an intermediate virtualenv to make my dependencies more flexible, which I think mirrors what you did manually.

**Comment by tgs** [comment]
Cool, thanks!

On Friday, January 16, 2015, Buck Golemon <notifications@github.com> wrote:

> Thanks for the feedback!
>
> You'll find that this is in my TODO for 1.0
> https://github.com/Yelp/venv-update/blob/v0.1/TODO#L8
>
> I'll make sure to cover the specific cases you mentioned.
>
> I also mentioned using an intermediate virtualenv to make my dependencies
> more flexible, which I think mirrors what you did manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Yelp/venv-update/issues/33#issuecomment-70334119>.
>


-- 
http://resc.smugmug.com/

**Comment by NorthIsUp** [comment]
#41 fixes this.

**Comment by bukzor** [comment]
@tgs I've merged #41 to master. Please try it?

**Comment by tgs** [comment]
Thanks!

That fixed it for my Python 3.3 installation!

It's still broken for 2.7.  It did correctly install pip, but it missed setuptools - I get

    ERROR: 'pip wheel' requires setuptools >= 0.8 for dist-info support. To fix this, run: pip install --upgrade setuptools

My crummy old virtualenv installs setuptools==0.6c11.  I'll understand if you don't want to target such an ancient version, but if it's not a big deal to have it upgrade itself, that'd be useful.

**Comment by bukzor** [comment]
I think this can have the same solution; we'd just install a proper setuptools version in the same spot.

If you patch it and show a clean travis, I'll merge.
